spring:
  datasource:
    url: jdbc:mysql://192.168.99.101:3306/real_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: 123456
server:
  port: 8004
redis:
  database: 1
  host: 192.168.99.101
  port: 6379
  lettuce:
    pool:
      max-active: 10

