spring:
  datasource:
    url: jdbc:mysql://192.168.99.101:3306/real_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: 123456
server:
  port: 8004
redis:
  database: 1
  host: 192.168.99.101
  port: 6379
  lettuce:
    pool:
      max-active: 10
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapping/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #数据库类型
      db-type: MYSQL
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

